In [26]:
# Import libraries
import pandas as pd
import numpy as np
import glob

In [27]:
# Read in Raw Data downloaded from FSS
df_std = pd.read_excel(r".\KICPA\VALUESearch_Standard.xlsx")

# Specify the column that needs renaming
old_column_name = '691005.업체명'
new_column_name = old_column_name.replace('691005.', '')
df_std.rename(columns={old_column_name: new_column_name}, inplace=True)

# Use REGEX to substitute substring
pattern1 = r'/[^/]+?\.'
pattern2 = r'\d+\.\w+-'
pattern3 = r'\(.*?\)'
pattern4 = r'^[A-Za-z]\d{5}\.'
df_std.columns = df_std.columns.str.replace(pattern1, '', regex=True)
df_std.columns = df_std.columns.str.replace(pattern2, '', regex=True)
df_std.columns = df_std.columns.str.replace(pattern3, '', regex=True)
df_std['대분류'] = df_std['대분류'].str.replace(pattern3, '', regex=True)
df_std['대분류'] = df_std['대분류'].str.replace(pattern4, '', regex=True)
df_std['중분류'] = df_std['중분류'].str.replace(pattern4, '', regex=True)
df_std['소분류'] = df_std['소분류'].str.replace(pattern4, '', regex=True)
df_std

,업체코드,종목코드,종목명,업체명,상장법인,2020감사법인,2021감사법인,2022감사법인,2023감사법인,2024감사법인,대분류,중분류,소분류
0,N840130,A000010,(주)신한은행,(주)신한은행,X,삼일회계법인,삼일회계법인,삼일회계법인,삼정회계법인,삼정회계법인,금융 및 보험업,금융업,은행 및 저축기관
1,N350605,A000020,동화약품,동화약품(주),O,한영회계법인,한영회계법인,한영회계법인,한울회계법인,NaN,제조업,의료용 물질 및 의약품 제조업,의약품 제조업
2,N840149,A000030,(주)우리은행,(주)우리은행,X,삼일회계법인,삼일회계법인,삼일회계법인,삼정회계법인,삼정회계법인,금융 및 보험업,금융업,은행 및 저축기관
3,N320498,A000040,KR모터스,KR모터스(주),O,인덕회계법인,인덕회계법인,인덕회계법인,삼일회계법인,NaN,제조업,기타 운송장비 제조업,그 외 기타 운송장비 제조업
4,N320684,A000050,경방,(주)경방,O,예교지성회계법인,예교지성회계법인,예교지성회계법인,한영회계법인,한영회계법인,도매 및 소매업,소매업; 자동차 제외,종합 소매업
...,...,...,...,...,...,...,...,...,...,...,...,...,...
39609,NX01379,NaN,다마요팩(주),다마요팩(주),X,NaN,참회계법인,참회계법인,참회계법인,NaN,제조업,"펄프, 종이 및 종이제품 제조업","골판지, 종이 상자 및 종이 용기 제조업"
39610,NX57312,NaN,(주)에스엘씨,(주)에스엘씨,X,광교회계법인,광교회계법인,광교회계법인,광교회계법인,NaN,제조업,화학 물질 및 화학제품 제조업; 의약품 제외,기타 화학제품 제조업
39611,NX91216,NaN,농업회사법인한국양계(주),농업회사법인한국양계(주),X,진일회계법인,진일회계법인,진일회계법인,진일회계법인,NaN,NaN,농업,축산업
39612,NY32604,NaN,(주)메디라인액티브코리아,(주)메디라인액티브코리아,X,한울회계법인,한울회계법인,한울회계법인,한울회계법인,NaN,제조업,"의료, 정밀, 광학 기기 및 시계 제조업",의료용 기기 제조업
39613,NY84181,NaN,(주)엘림글로벌,(주)엘림글로벌,X,NaN,NaN,NaN,NaN,NaN,도매 및 소매업,도매 및 상품 중개업,기계장비 및 관련 물품 도매업

In [28]:
# List of file paths and corresponding DataFrames
file_paths = [
    r".\KICPA\VALUESearch1_Liability.xlsx",
    r".\KICPA\VALUESearch2_Goodwill.xlsx",
    r".\KICPA\VALUESearch2_Development.xlsx",
    r".\KICPA\VALUESearch2_Other_Intagibles.xlsx",
    r".\KICPA\VALUESearch4_LiquidityRatio.xlsx"
]

# Read and process each file
dataframes = []
for path in file_paths:
    df = pd.read_excel(path)
    df.columns = df.columns.str.replace(pattern1, '', regex=True)
    dataframes.append(df)

# Merge all DataFrames with the base DataFrame df_std
df = df_std
for df_add in dataframes:
    df = pd.merge(df, df_add, on=['업체코드', '종목코드', '종목명'], how='left')

# Print or check the final DataFrame
df

,업체코드,종목코드,종목명,업체명,상장법인,2020감사법인,2021감사법인,2022감사법인,2023감사법인,2024감사법인,...,2020유동자산(계),2021유동자산(계),2022유동자산(계),2023유동자산(계),2024유동자산(계),2020유동부채(계),2021유동부채(계),2022유동부채(계),2023유동부채(계),2024유동부채(계)
0,N840130,A000010,(주)신한은행,(주)신한은행,X,삼일회계법인,삼일회계법인,삼일회계법인,삼정회계법인,삼정회계법인,...,0,0,0,0,0,0,0,0,0,0
1,N350605,A000020,동화약품,동화약품(주),O,한영회계법인,한영회계법인,한영회계법인,한울회계법인,NaN,...,204761409000,198384409000,200259833000,168595422000,179314300000,53627734000,57463664000,66243507000,72220674000,81727276000
2,N840149,A000030,(주)우리은행,(주)우리은행,X,삼일회계법인,삼일회계법인,삼일회계법인,삼정회계법인,삼정회계법인,...,0,0,0,0,0,0,0,0,0,0
3,N320498,A000040,KR모터스,KR모터스(주),O,인덕회계법인,인덕회계법인,인덕회계법인,삼일회계법인,NaN,...,10500589000,9165496000,10920685000,10279597000,11383710000,49161195000,47619046000,53860176000,61033237000,68163909000
4,N320684,A000050,경방,(주)경방,O,예교지성회계법인,예교지성회계법인,예교지성회계법인,한영회계법인,한영회계법인,...,67253983000,66773086000,51942911000,76098399000,91966797000,222570410000,163333450000,89633813000,190926534000,210047307000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39609,NX01379,NaN,다마요팩(주),다마요팩(주),X,NaN,참회계법인,참회계법인,참회계법인,NaN,...,2757498000,3572163000,3744764000,4235804000,0,4919634000,5655918000,6200893000,9033689000,0
39610,NX57312,NaN,(주)에스엘씨,(주)에스엘씨,X,광교회계법인,광교회계법인,광교회계법인,광교회계법인,NaN,...,2682938000,7176026000,5222069000,13373900000,0,8100238000,8678293000,8809533000,2806502000,0
39611,NX91216,NaN,농업회사법인한국양계(주),농업회사법인한국양계(주),X,진일회계법인,진일회계법인,진일회계법인,진일회계법인,NaN,...,10459422000,18564994000,12821718000,13878284000,0,6130805000,9876131000,5735405000,4951108000,0
39612,NY32604,NaN,(주)메디라인액티브코리아,(주)메디라인액티브코리아,X,한울회계법인,한울회계법인,한울회계법인,한울회계법인,NaN,...,13308796000,14080773000,14687463000,16626001000,0,7332902000,8132800000,13837758000,15708320000,0
39613,NY84181,NaN,(주)엘림글로벌,(주)엘림글로벌,X,NaN,NaN,NaN,NaN,NaN,...,4161782000,3973396000,4578160000,4991631000,0,1781562000,1310398000,1340421000,295486000,0

In [29]:
# Retrieve the list of companies with Debt Issuance in the recent 3 years (2021-08-13 ~ 2024-08-13)
df_debt = pd.read_excel(r".\KICPA\VALUESearch4_DebtIssuance.xls")

df_debt = df_debt['회사명'].drop_duplicates().reset_index(drop=True)
debt_list = df_debt.to_list()

# Create the 'Debt Issued' column based on whether the company is in debt_list
df['채무증권발행(최근 3년)'] = df['종목명'].apply(lambda x: 'O' if x in debt_list else 'X')
df

,업체코드,종목코드,종목명,업체명,상장법인,2020감사법인,2021감사법인,2022감사법인,2023감사법인,2024감사법인,...,2021유동자산(계),2022유동자산(계),2023유동자산(계),2024유동자산(계),2020유동부채(계),2021유동부채(계),2022유동부채(계),2023유동부채(계),2024유동부채(계),채무증권발행(최근 3년)
0,N840130,A000010,(주)신한은행,(주)신한은행,X,삼일회계법인,삼일회계법인,삼일회계법인,삼정회계법인,삼정회계법인,...,0,0,0,0,0,0,0,0,0,X
1,N350605,A000020,동화약품,동화약품(주),O,한영회계법인,한영회계법인,한영회계법인,한울회계법인,NaN,...,198384409000,200259833000,168595422000,179314300000,53627734000,57463664000,66243507000,72220674000,81727276000,X
2,N840149,A000030,(주)우리은행,(주)우리은행,X,삼일회계법인,삼일회계법인,삼일회계법인,삼정회계법인,삼정회계법인,...,0,0,0,0,0,0,0,0,0,X
3,N320498,A000040,KR모터스,KR모터스(주),O,인덕회계법인,인덕회계법인,인덕회계법인,삼일회계법인,NaN,...,9165496000,10920685000,10279597000,11383710000,49161195000,47619046000,53860176000,61033237000,68163909000,X
4,N320684,A000050,경방,(주)경방,O,예교지성회계법인,예교지성회계법인,예교지성회계법인,한영회계법인,한영회계법인,...,66773086000,51942911000,76098399000,91966797000,222570410000,163333450000,89633813000,190926534000,210047307000,X
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39609,NX01379,NaN,다마요팩(주),다마요팩(주),X,NaN,참회계법인,참회계법인,참회계법인,NaN,...,3572163000,3744764000,4235804000,0,4919634000,5655918000,6200893000,9033689000,0,X
39610,NX57312,NaN,(주)에스엘씨,(주)에스엘씨,X,광교회계법인,광교회계법인,광교회계법인,광교회계법인,NaN,...,7176026000,5222069000,13373900000,0,8100238000,8678293000,8809533000,2806502000,0,X
39611,NX91216,NaN,농업회사법인한국양계(주),농업회사법인한국양계(주),X,진일회계법인,진일회계법인,진일회계법인,진일회계법인,NaN,...,18564994000,12821718000,13878284000,0,6130805000,9876131000,5735405000,4951108000,0,X
39612,NY32604,NaN,(주)메디라인액티브코리아,(주)메디라인액티브코리아,X,한울회계법인,한울회계법인,한울회계법인,한울회계법인,NaN,...,14080773000,14687463000,16626001000,0,7332902000,8132800000,13837758000,15708320000,0,X
39613,NY84181,NaN,(주)엘림글로벌,(주)엘림글로벌,X,NaN,NaN,NaN,NaN,NaN,...,3973396000,4578160000,4991631000,0,1781562000,1310398000,1340421000,295486000,0,X

In [30]:
# Melting process

# List of columns to melt
value_vars_audit_firm = ['2020감사법인', '2021감사법인', '2022감사법인', '2023감사법인', '2024감사법인']
value_vars_total_revenue = ['2020총수익', '2021총수익', '2022총수익', '2023총수익', '2024총수익']
value_vars_repair_provision = ['2020하자보수충당부채', '2021하자보수충당부채', '2022하자보수충당부채', '2023하자보수충당부채', '2024하자보수충당부채']
value_vars_warranty_provision = ['2020판매보증충당부채', '2021판매보증충당부채', '2022판매보증충당부채', '2023판매보증충당부채', '2024판매보증충당부채']
value_vars_construction_loss_provision = ['2020공사손실충당부채', '2021공사손실충당부채', '2022공사손실충당부채', '2023공사손실충당부채', '2024공사손실충당부채']
value_vars_guarantee_loss_provision = ['2020보증손실충당부채', '2021보증손실충당부채', '2022보증손실충당부채', '2023보증손실충당부채', '2024보증손실충당부채']
value_vars_goodwill = ['2020영업권', '2021영업권', '2022영업권', '2023영업권', '2024영업권']
value_vars_goodwill_acc_depreciation = ['2020(영업권상각누계액)', '2021(영업권상각누계액)', '2022(영업권상각누계액)', '2023(영업권상각누계액)', '2024(영업권상각누계액)']
value_vars_goodwill_acc_impairment = ['2020(영업권손상차손누계액)', '2021(영업권손상차손누계액)', '2022(영업권손상차손누계액)', '2023(영업권손상차손누계액)', '2024(영업권손상차손누계액)']
value_vars_goodwill_gov_subsidiary = ['2020(영업권정부보조금)', '2021(영업권정부보조금)', '2022(영업권정부보조금)', '2023(영업권정부보조금)', '2024(영업권정부보조금)']
value_vars_development = ['2020개발비', '2021개발비', '2022개발비', '2023개발비', '2024개발비']
value_vars_development_acc_depreciation = ['2020(개발비상각누계액)', '2021(개발비상각누계액)', '2022(개발비상각누계액)', '2023(개발비상각누계액)', '2024(개발비상각누계액)']
value_vars_development_acc_impairment = ['2020(개발비손상차손누계액)', '2021(개발비손상차손누계액)', '2022(개발비손상차손누계액)', '2023(개발비손상차손누계액)', '2024(개발비손상차손누계액)']
value_vars_development_gov_subsidiary = ['2020(개발비정부보조금)', '2021(개발비정부보조금)', '2022(개발비정부보조금)', '2023(개발비정부보조금)', '2024(개발비정부보조금)']
value_vars_other = ['2020기타무형자산', '2021기타무형자산', '2022기타무형자산', '2023기타무형자산', '2024기타무형자산']
value_vars_other_acc_depreciation = ['2020(기타무형자산상각누계액)', '2021(기타무형자산상각누계액)', '2022(기타무형자산상각누계액)', '2023(기타무형자산상각누계액)', '2024(기타무형자산상각누계액)']
value_vars_other_acc_impairment = ['2020(기타무형자산손상차손누계액)', '2021(기타무형자산손상차손누계액)', '2022(기타무형자산손상차손누계액)', '2023(기타무형자산손상차손누계액)', '2024(기타무형자산손상차손누계액)']
value_vars_other_gov_subsidiary = ['2020(기타무형자산정부보조금)', '2021(기타무형자산정부보조금)', '2022(기타무형자산정부보조금)', '2023(기타무형자산정부보조금)', '2024(기타무형자산정부보조금)']
value_vars_current_asset = ['2020유동자산(계)', '2021유동자산(계)', '2022유동자산(계)', '2023유동자산(계)', '2024유동자산(계)']
value_vars_current_liability = ['2020유동부채(계)', '2021유동부채(계)', '2022유동부채(계)', '2023유동부채(계)', '2024유동부채(계)']

# Melting the data for all columns at once
df_melt = pd.melt(df,
                  id_vars=['업체코드', '종목코드', '종목명', '업체명', '상장법인', '대분류', '중분류', '소분류', '채무증권발행(최근 3년)'],
                  value_vars=value_vars_audit_firm + value_vars_total_revenue + value_vars_repair_provision + value_vars_warranty_provision + value_vars_construction_loss_provision + 
                  value_vars_guarantee_loss_provision + value_vars_goodwill + value_vars_goodwill_acc_depreciation + value_vars_goodwill_acc_impairment + value_vars_goodwill_gov_subsidiary +
                  value_vars_development + value_vars_development_acc_depreciation + value_vars_development_acc_impairment + value_vars_development_gov_subsidiary +
                  value_vars_other + value_vars_other_acc_depreciation + value_vars_other_acc_impairment + value_vars_other_gov_subsidiary +
                  value_vars_current_asset + value_vars_current_liability,
                  var_name='연도_항목',
                  value_name='값')


# Extracting the year and the type of value into each column: 연도 | 항목
df_melt['연도'] = df_melt['연도_항목'].str[:4]
df_melt['항목'] = df_melt['연도_항목'].str[4:]

df_melt.loc[df_melt['항목'] != '감사법인', '값'] = pd.to_numeric(df_melt.loc[df_melt['항목'] != '감사법인', '값'], errors='coerce')

# df_melt

# Use pivot to reshape the DataFrame
df_pivot = df_melt.pivot(index=['업체코드', '종목코드', '종목명', '업체명', '상장법인', '대분류', '중분류', '소분류', '채무증권발행(최근 3년)', '연도'], 
                         columns='항목', 
                         values='값')

# Reset index to make it a DataFrame again
df_pivot = df_pivot.reset_index()

# Fill missing values if necessary
df_pivot = df_pivot.fillna('')  # or fillna('your_value') depending on your needs

df_pivot

C:\Users\jaecjung\AppData\Local\Temp\ipykernel_13532\76814774.py:54: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_pivot = df_pivot.fillna('')  # or fillna('your_value') depending on your needs

항목,업체코드,종목코드,종목명,업체명,상장법인,대분류,중분류,소분류,채무증권발행(최근 3년),연도,...,개발비,공사손실충당부채,기타무형자산,보증손실충당부채,영업권,유동부채(계),유동자산(계),총수익,판매보증충당부채,하자보수충당부채
0,N000167,,에이엠플러스인덕원(주),에이엠플러스인덕원(주),X,부동산업,부동산업,부동산 임대 및 공급업,X,2020,...,0,0,0,0,0,31150000,1411050000,411425000,0,0
1,N000167,,에이엠플러스인덕원(주),에이엠플러스인덕원(주),X,부동산업,부동산업,부동산 임대 및 공급업,X,2021,...,0,0,0,0,0,30632000,778895000,412255000,0,0
2,N000167,,에이엠플러스인덕원(주),에이엠플러스인덕원(주),X,부동산업,부동산업,부동산 임대 및 공급업,X,2022,...,0,0,0,0,0,3192305000,67484527000,1229721000,0,0
3,N000167,,에이엠플러스인덕원(주),에이엠플러스인덕원(주),X,부동산업,부동산업,부동산 임대 및 공급업,X,2023,...,0,0,0,0,0,4857530000,85267087000,13632747000,0,0
4,N000167,,에이엠플러스인덕원(주),에이엠플러스인덕원(주),X,부동산업,부동산업,부동산 임대 및 공급업,X,2024,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198065,NY84181,,(주)엘림글로벌,(주)엘림글로벌,X,도매 및 소매업,도매 및 상품 중개업,기계장비 및 관련 물품 도매업,X,2020,...,864026000,0,0,0,384000000,1781562000,4161782000,4600397000,0,0
198066,NY84181,,(주)엘림글로벌,(주)엘림글로벌,X,도매 및 소매업,도매 및 상품 중개업,기계장비 및 관련 물품 도매업,X,2021,...,887025000,0,0,0,384000000,1310398000,3973396000,5560033000,0,0
198067,NY84181,,(주)엘림글로벌,(주)엘림글로벌,X,도매 및 소매업,도매 및 상품 중개업,기계장비 및 관련 물품 도매업,X,2022,...,1082404000,0,0,0,384000000,1340421000,4578160000,6622261000,0,0
198068,NY84181,,(주)엘림글로벌,(주)엘림글로벌,X,도매 및 소매업,도매 및 상품 중개업,기계장비 및 관련 물품 도매업,X,2023,...,1429340000,0,0,0,384000000,295486000,4991631000,7716645000,0,0
198069,NY84181,,(주)엘림글로벌,(주)엘림글로벌,X,도매 및 소매업,도매 및 상품 중개업,기계장비 및 관련 물품 도매업,X,2024,...,0,0,0,0,0,0,0,0,0,0

In [31]:
# Export to excel
df_pivot.to_excel("KICPA_중점심사.xlsx", index=False)